#define TOK_AND                              1
#define TOK_OR                               2
#define TOK_NOT                              3
#define TOK_SEMICOLON                        4
#define TOK_LBRACKET                         5
#define TOK_RBRACKET                         6
#define TOK_TRUE                             7
#define TOK_FALSE                            8
#define TOK_IDENT                            9
